### ISSUE TITLE
Ajouter le dossier BDD au .gitignore ? 

### ISSUE THREAD

**Issue by loicbourgois** [eleves-ig2i/ig2i-le4-poo-2018-tp2#2]
@Hercules0402 : le dossier bdd/ est obligatoire pour le bon fonctionnement ? 
Ou alors il est regénéré quand on lance le code ?

**Comment by Hercules0402** [comment]
Il contient la bdd (il n'est pas obligatoire)

**Comment by loicbourgois** [comment]
fixed in https://github.com/eleves-ig2i/ig2i-le4-poo-2018-tp-2/pull/4
