### ISSUE TITLE
Connection refused because the database was not found

### ISSUE THREAD

**Issue by loicbourgois** [eleves-ig2i/ig2i-le4-poo-2018-tp2#6]
Je vois 2 solutions pour ce problème : 
- ajouter une commande dans `gulpfile.js` qui configure correctement la base de donnée ; 
- indiquer dans le readme comment configurer la BDD, avec username, db name et password. 
Les logs : 
```Internal Exception: java.sql.SQLNonTransientConnectionException: The connection was refused because the database hopital was not found.
Error Code: 40000
Exception in thread "main" javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLNonTransientConnectionException: The connection was refused because the database hopital was not found.```

**Comment by Hercules0402** [comment]
@loicbourgois  : Je vais rajouter les infos nécessaires dans le readme

**Comment by loicbourgois** [comment]
Résolu en suivant les nouvelles informations du readme ajoutées via https://github.com/eleves-ig2i/ig2i-le4-poo-2018-tp2/pull/7
